# Generated by Django 6.0.6 on 2026-07-23 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('order', '0003_order_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='order.order'),
        ),
    ]
