# Generated by Django 6.0.6 on 2026-07-03 10:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', '待付款'), ('PAID', '已付款'), ('SHIPPED', '已出貨'), ('COMPLETED', '已完成'), ('REFUNDED', '已退款')], default='PENDING', max_length=12),
        ),
    ]
