# Generated by Django 6.0.6 on 2026-07-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', '待付款'), ('AWAITING', '待出貨'), ('SHIPPED', '已出貨'), ('CANCELLED', '已取消')], default='PENDING', max_length=12),
        ),
    ]
