# Generated by Django 6.0.6 on 2026-07-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contact_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='聯絡人'),
        ),
        migrations.AddField(
            model_name='order',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='聯絡人電話'),
        ),
        migrations.AddField(
            model_name='order',
            name='expected_ship_date',
            field=models.DateField(blank=True, null=True, verbose_name='預計出貨日'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=200, verbose_name='收貨地址'),
        ),
    ]
